# Generated by Django 5.2.2 on 2025-06-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=30)),
                ('sobrenome', models.TextField(max_length=30)),
                ('email', models.TextField(max_length=70)),
                ('recebe_notificacao', models.BooleanField()),
                ('tipo_usuario', models.IntegerField(choices=[(1, 'Aluno'), (2, 'Aluno Expositor'), (3, 'Professor'), (4, 'Professor de outra IESS'), (5, 'Avaliador'), (6, 'Visitante')], default=1, max_length=1)),
            ],
        ),
    ]
