# Generated by Django 5.2.2 on 2025-06-10 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_union', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='instituicao_matriz',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nome_projeto',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ra',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tema_trabalho',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='uc',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
    ]
